import type { Metadata } from "next"
import Header from "@/components/Header"
import "./globals.css"
import { Roboto } from "next/font/google"
import Footer from "@/components/Footer"
import { headerButtons, menuListData } from "@/constants"
import { Toaster } from "@/components/ui/toaster"
import { VisualEditing } from "next-sanity"
import { draftMode } from "next/headers"
import { ViewTransitions } from "next-view-transitions"

const roboto = Roboto({
  weight: ["400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ViewTransitions>
      <html lang="en" className={roboto.className}>
        <body>
          {draftMode().isEnabled && (
            <div>
              <a className="p-4 bg-blue-300 block" href="/api/disable-draft">
                Disable preview mode
              </a>
            </div>
          )}
          <div>
            <Header menuListHeader={menuListData} />
            {children}
            <Footer />
          </div>
          <Toaster />

          {draftMode().isEnabled && <VisualEditing />}
        </body>
      </html>
    </ViewTransitions>
  )
}
