import Header from "@/components/Header"
import "./globals.css"
import type { Metadata } from "next"
import { Roboto } from "next/font/google"
import Footer from "@/components/Footer"
import { headerButtons, menuListData } from "@/constants"

const roboto = Roboto({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div>
          <Header menuListHeader={menuListData} btnData={headerButtons} />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
